spring:
  datasource:
    #password: maxu030510@#
    password: adminxupt
    username: root
    url: jdbc:mysql://39.97.179.77:3306/tmp?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    #url: jdbc:mysql://cdb-eo0fbe96.bj.tencentcdb.com:10223/tmp?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver


springfox:
  documentation:
    swagger:
      v1:
        path: /api-doc

mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.xupt.tmp.domain

pagehelper:
  supportMethodsArguments: true
  reasonable: true
  returnPageInfo: check
  helperDialect: mysql
  params: count=countSql
